#!/bin/sh
bucket=diogenes-jenkins
dir=/usr/local/jenkins
warfile=/usr/local/share/jenkins/jenkins.war
dirobject=jenkins.tar.gz
warobject=jenkins.war
tmpbase=`basename ${0}`
tmpfile=`mktemp /tmp/${tmpbase}.XXXX` || exit 1
trap 'rm "${tmpfile}"' EXIT
tar -C "${dir}" -czf "${tmpfile}" .
/usr/local/bin/aws s3 cp "${tmpfile}" "s3://${bucket}/${dirobject}"
/usr/local/bin/aws s3 cp "${warfile}" "s3://${bucket}/${warobject}"
